pull_request_rules:
  - name: Automatic merge for scala-steward pull requests
    conditions:
      - author=scala-steward
      - status-success=Test / Status (pull_request)
    actions:
      merge:
        method: merge

  - name: Labeling for Scala Steward PR's
    conditions:
      - author=scala-steward
    actions:
      label:
        add: [ "type:updates" ]
